import { config } from "@/const/config";

const nfts_list = [
  // 1.nft角色卡 nft_role
  // 2.战法道具卡 tactics_props
  // 3.出征令牌 expedition_order
  // 4.合成道具卡 synthesis_props
  // 5.财神卡 fortune_card

  //nft角色卡

  //武圣出山阶段
  {
    id: 1,
    name: "美髯公",
    stage: "武聖出山",
    card_type: "nft_role",
    next_nft_id: 2,
    next_need_nfts: [1, 31, 32],
    outbound_tokens_id: 81,
    imageUrl: `${config.api}/role/1_2.png`,
    upgrade_requirements: "美髯公 + 赤兔馬 + 青龍偃月刀",
    price: "400",
    outbound_tokens: "關公令",
    token_value: "150",
    cycle: "1週",
    monthly_interest_rate: "24%",
    loss_period: 135,
  },
  {
    id: 2,
    name: "漢壽侯",
    stage: "武聖出山",
    card_type: "nft_role",
    next_nft_id: 3,
    next_need_nfts: [2, 33, 34, 35],
    outbound_tokens_id: 81,
    imageUrl: `${config.api}/role/2_2.png`,
    upgrade_requirements: "漢壽侯 + 周倉 + 關平 + 廖化",
    price: "600",
    outbound_tokens: "關公令",
    token_value: "150",
    cycle: "1週",
    monthly_interest_rate: "32%",
    loss_period: 150,
  },
  {
    id: 3,
    name: "武聖",
    stage: "武聖出山",
    card_type: "nft_role",
    next_nft_id: 4,
    next_need_nfts: [3, 36, 37],
    outbound_tokens_id: 81,
    imageUrl: `${config.api}/role/3_2.png`,
    upgrade_requirements: "武聖 + 張飛 + 劉備",
    price: "900",
    outbound_tokens: "關公令",
    token_value: "150",
    cycle: "1週",
    monthly_interest_rate: "44%",
    loss_period: 165,
  },
  //nft角色卡百战封神阶段
  {
    id: 4,
    name: "桃園結義",
    stage: "百戰封神",
    card_type: "nft_role",
    next_nft_id: 5,
    next_need_nfts: [3, 38, 39, 40],
    outbound_tokens_id: 82,
    imageUrl: `${config.api}/role/4_2.png`,
    upgrade_requirements: "武圣+曹仁+于禁+庞德",
    price: "1500",
    outbound_tokens: "結義令",
    token_value: "600",
    cycle: "1月",
    monthly_interest_rate: "28%",
    loss_period: 36,
  },
  {
    id: 5,
    name: "水淹七军",
    stage: "百戰封神",
    card_type: "nft_role",
    next_nft_id: 6,
    next_need_nfts: [3, 36, 41, 42, 43],
    outbound_tokens_id: 83,
    imageUrl: `${config.api}/role/5_2.png`,
    upgrade_requirements: "武圣+张飞+赵云+马超+黄忠",
    price: "1800",
    outbound_tokens: "擒将令",
    token_value: "600",
    cycle: "1 月",
    monthly_interest_rate: "36%",
    loss_period: 34,
  },
  {
    id: 6,
    name: "五虎上将",
    stage: "百戰封神",
    card_type: "nft_role",
    next_nft_id: 7,
    next_need_nfts: [3, 40, 44, 45, 46],
    outbound_tokens_id: 84,
    imageUrl: `${config.api}/role/6_2.png`,
    upgrade_requirements: "武圣+华雄+颜良+文丑+庞德",
    price: "2100",
    outbound_tokens: "拜将令",
    token_value: "700",
    cycle: "1 月",
    monthly_interest_rate: "40%",
    loss_period: 30,
  },
  {
    id: 7,
    name: "威震华夏",
    stage: "百戰封神",
    card_type: "nft_role",
    next_nft_id: 8,
    next_need_nfts: [3, 48, 49, 50, 51, 52, 53, 54],
    outbound_tokens_id: 85,
    imageUrl: `${config.api}/role/7_2.png`,
    upgrade_requirements: "武圣+孔秀+孟坦+韩福+卞喜+王植+秦琪+蔡阳",
    price: "2100",
    outbound_tokens: "斩将令",
    token_value: "800",
    cycle: "1 月",
    monthly_interest_rate: "40%",
    loss_period: 27,
  },
  {
    id: 8,
    name: "千里单骑",
    stage: "百戰封神",
    card_type: "nft_role",
    next_nft_id: 9,
    next_need_nfts: [3, 55, 56, 57, 58],
    outbound_tokens_id: 86,
    imageUrl: `${config.api}/role/8_2.png`,
    upgrade_requirements: "武圣+忠+义+仁+勇",
    price: "3000",
    outbound_tokens: "通关令",
    token_value: "1000",
    cycle: "1 月",
    monthly_interest_rate: "38%",
    loss_period: 32,
  },
  // nft角色卡 万世流芳阶段
  {
    id: 9,
    name: "忠義仁勇武財神",
    stage: "萬世流芳",
    card_type: "nft_role",
    outbound_tokens_id: 87,
    imageUrl: `${config.api}/role/9_2.png`,
    upgrade_requirements: "武圣+忠+义+仁+勇",
    price: "4500",
    outbound_tokens: "财神令",
    token_value: "2000",
    cycle: "2月",
    monthly_interest_rate: "60%",
    loss_period: 20,
  },

  //战法道具卡
  {
    id: 59,
    name: "華佗",
    tag: "战法道具卡",
    card_type: "tactics_props",
    imageUrl: `${config.api}prop_method/59_2.png`,
    number_of_issues: "100萬張",
    prop_features:
      "获得“刮骨疗毒”战法 1 次；使用本战法，可花费角色价值的 70%USDT，将“关公荣耀卡”的损耗周期重置。",
    target: "無限制",
    price: "100",
    tips: "注意：增益道具卡的收益率增幅降幅均以出征令牌价格为基准。",
  },
  {
    id: 60,
    name: "张角",
    tag: "战法道具卡",
    card_type: "tactics_props",
    imageUrl: `${config.api}prop_method/60_2.png`,
    number_of_issues: "10 万张",
    prop_features:
      "获得“太平道法”战法 1 次；可让自己第一代被推荐账户中所有角色下次出征时长增加 5%；出征收益增加 2%，且其中 1%划归自己。已经获得过增益效果的账户获得 1 次免疫期。",
    target: "只能对自己使用",
    price: "300",
    tips: "注意：增益道具卡的收益率增幅降幅均以出征令牌价格为基准。",
  },
  {
    id: 61,
    name: "诸葛亮",
    tag: "战法道具卡",
    card_type: "tactics_props",
    imageUrl: `${config.api}prop_method/61_2.png`,
    number_of_issues: "10 万张",
    prop_features:
      "获得“草船借箭”战法 1 次；使用后可使自身账户和旗下直属第一代排名前 3 的被推荐账户的所有角色损耗周期延长 1 次（但该次出征时长延长 30%）；每个角色在每个损耗周期中只能接受 1 次“草船借箭”。",
    target: "無限制",
    price: "1000",
    tips: "注意：增益道具卡的收益率增幅降幅均以出征令牌价格为基准。",
  },
  {
    id: 62,
    name: "孟获",
    tag: "战法道具卡",
    card_type: "tactics_props",
    imageUrl: `${config.api}prop_method/62_2.png`,
    number_of_issues: "10 万张",
    prop_features:
      "获得“南蛮入侵”战法 1 次；使用本卡可窃取遭受“南蛮入侵”的账号及旗下第一代推荐账户中所有角色下次出征收益的 1%。遭受过“南蛮入侵”的账号享有 3 次免疫期。",
    target: "只能对他人使用",
    price: "500",
    tips: "注意：增益道具卡的收益率增幅降幅均以出征令牌价格为基准。",
  },
  {
    id: 63,
    name: "袁术",
    card_type: "tactics_props",
    imageUrl: `${config.api}prop_method/63_2.png`,
    tag: "战法道具卡",
    number_of_issues: "10 万张",
    prop_features:
      "可获得“窃印称帝”战法 1 次；使用后，账号中的所有角色下次出征收益提升 6%（该次出征时长增加 2 天）；第一代推荐账号的所有角色下一次出征损失 2%收益，减少 5%出征时间；获得过本效果的账号具有 2 次免疫期。",
    target: "无限制",
    price: "200",
    tips: "注意：增益道具卡的收益率增幅降幅均以出征令牌价格为基准。",
  },

  //出征令牌
  {
    id: 81,
    imageUrl: `${config.api}/token/81_2.png`,
    tag: "出征令牌",
    name: "关公令",
    price: "150",
    card_type: "expedition_order",
    can_be_used: ["美髯公", "汉寿侯", "武圣"],
  },
  {
    id: 82,
    imageUrl: `${config.api}/token/82_2.png`,
    tag: "出征令牌",
    name: "结义令",
    price: "600",
    card_type: "expedition_order",
    can_be_used: ["桃园结义"],
  },
  {
    id: 83,
    imageUrl: `${config.api}/token/83_2.png`,
    tag: "出征令牌",
    name: "擒将令",
    price: "600",
    card_type: "expedition_order",
    can_be_used: ["水淹七军"],
  },
  {
    id: 84,
    imageUrl: `${config.api}/token/84_2.png`,
    tag: "出征令牌",
    name: "拜将令",
    price: "700",
    card_type: "expedition_order",
    can_be_used: ["五虎上将"],
  },
  {
    id: 85,
    imageUrl: `${config.api}/token/85_2.png`,
    tag: "出征令牌",
    name: "斩将令",
    price: "800",
    card_type: "expedition_order",
    can_be_used: ["威震华夏"],
  },
  {
    id: 86,
    imageUrl: `${config.api}/token/86_2.png`,
    tag: "出征令牌",
    name: "通关令",
    price: "1000",
    card_type: "expedition_order",
    can_be_used: ["千里单骑"],
  },
  {
    id: 87,
    imageUrl: `${config.api}/token/87_2.png`,
    tag: "出征令牌",
    name: "财神令",
    price: "2000",
    card_type: "expedition_order",
    can_be_used: ["忠义仁勇武财神"],
  },

  //合成道具卡
  {
    id: 31,
    imageUrl: `${config.api}/prop_synth/31_2.png`,
    tag: "合成道具卡",
    card_type: "synthesis_props",
    name: "赤兔马",
    price: "100",
  },
  {
    id: 32,
    imageUrl: `${config.api}/prop_synth/32_2.png`,
    tag: "合成道具卡",
    card_type: "synthesis_props",
    name: "青龙偃月刀",
    price: "100",
  },
  {
    id: 33,
    imageUrl: `${config.api}/prop_synth/33_2.png`,
    tag: "合成道具卡",
    card_type: "synthesis_props",
    name: "周仓",
    price: "100",
  },
  {
    id: 34,
    name: "关平",
    imageUrl: `${config.api}/prop_synth/34_2.png`,
    tag: "合成道具卡",
    card_type: "synthesis_props",
    price: "100",
  },
  {
    id: 35,
    imageUrl: `${config.api}/prop_synth/35_2.png`,
    tag: "合成道具卡",
    card_type: "synthesis_props",
    name: "廖化",
    price: "100",
  },
  {
    id: 36,
    imageUrl: `${config.api}/prop_synth/36_2.png`,
    tag: "合成道具卡",
    card_type: "synthesis_props",
    name: "张飞",
    price: "300",
  },
  {
    id: 37,
    imageUrl: `${config.api}/prop_synth/37_2.png`,
    tag: "合成道具卡",
    card_type: "synthesis_props",
    name: "刘备",
    price: "300",
  },
  {
    id: 38,
    imageUrl: `${config.api}/prop_synth/38_2.png`,
    tag: "合成道具卡",
    card_type: "synthesis_props",
    name: "曹仁",
    price: "300",
  },
  {
    id: 39,
    imageUrl: `${config.api}/prop_synth/39_2.png`,
    tag: "合成道具卡",
    card_type: "synthesis_props",
    name: "于禁",
    price: "300",
  },
  {
    id: 40,
    imageUrl: `${config.api}/prop_synth/40_2.png`,
    tag: "合成道具卡",
    card_type: "synthesis_props",
    name: "庞德",
    price: "300",
  },
  {
    id: 41,
    imageUrl: `${config.api}/prop_synth/41_2.png`,
    tag: "合成道具卡",
    card_type: "synthesis_props",
    name: "赵云",
    price: "300",
  },
  {
    id: 42,
    name: "马超",
    imageUrl: `${config.api}/prop_synth/42_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    price: "300",
  },
  {
    id: 43,
    imageUrl: `${config.api}/prop_synth/43_2.png`,
    card_type: "synthesis_props",
    name: "黄忠",
    tag: "合成道具卡",
    price: "300",
  },
  {
    id: 44,
    imageUrl: `${config.api}/prop_synth/44_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    name: "华雄",
    price: "300",
  },
  {
    id: 45,
    name: "颜良",
    imageUrl: `${config.api}/prop_synth/45_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    price: "300",
  },
  {
    id: 46,
    name: "文丑",
    imageUrl: `${config.api}/prop_synth/46_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    price: "300",
  },
  {
    id: 47,
    name: "庞德",
    imageUrl: `${config.api}/prop_synth/40_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    price: "300",
  },
  {
    id: 48,
    imageUrl: `${config.api}/prop_synth/48_2.png`,
    card_type: "synthesis_props",
    name: "孔秀",
    tag: "合成道具卡",
    price: "300",
  },
  {
    id: 49,
    imageUrl: `${config.api}/prop_synth/49_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    name: "孟坦",
    price: "300",
  },
  {
    id: 50,
    name: "韩福",
    imageUrl: `${config.api}/prop_synth/50_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    price: "300",
  },
  {
    id: 51,
    name: "卞喜",
    imageUrl: `${config.api}/prop_synth/51_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    price: "300",
  },
  {
    id: 52,
    name: "王植",
    imageUrl: `${config.api}/prop_synth/52_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    price: "300",
  },
  {
    id: 53,
    name: "秦琪",
    imageUrl: `${config.api}/prop_synth/53_2.png`,
    card_type: "synthesis_props",
    tag: "出征令牌",
    price: "300",
  },
  {
    id: 54,
    name: "蔡阳",
    imageUrl: `${config.api}/prop_synth/54_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    price: "300",
  },
  {
    id: 55,
    name: "忠",
    imageUrl: `${config.api}/prop_synth/55_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    price: "900",
  },
  {
    id: 56,
    name: "义",
    imageUrl: `${config.api}/prop_synth/56_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    price: "900",
  },
  {
    id: 57,
    name: "仁",
    imageUrl: `${config.api}/prop_synth/57_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    price: "900",
  },
  {
    id: 58,
    name: "勇",
    imageUrl: `${config.api}/prop_synth/58_2.png`,
    card_type: "synthesis_props",
    tag: "合成道具卡",
    price: "900",
  },

  //财神卡
  {
    id: 10,
    name: "贤人武财神",
    level: "忠字传播大使",
    imageUrl: `${config.api}/wealth/10_2.png`,
    card_type: "fortune_card",
    circulation: 100,
    award: 104.6666667,
    cycle: 7,
    price: "100",
  },

  {
    id: 11,
    name: "真人武财神",
    level: "忠字传播大使",
    imageUrl: `${config.api}/wealth/11_2.png`,
    card_type: "fortune_card",
    circulation: 500,
    award: 552.5,
    cycle: 15,
    price: "500",
  },
  {
    id: 12,
    name: "仙人武财神",
    level: "忠字传播大使",
    imageUrl: `${config.api}/wealth/12_2.png`,
    card_type: "fortune_card",
    circulation: 1000,
    award: 1220,
    cycle: 30,
    price: "1000",
  },
  {
    id: 13,
    name: "道人武财神",
    level: "义字传播大使",
    imageUrl: `${config.api}/wealth/13_2.png`,
    card_type: "fortune_card",
    circulation: 3000,
    award: 3690,
    cycle: 30,
    price: "3000",
  },
  {
    id: 14,
    name: "圣人武财神",
    level: "仁字传播大使",
    imageUrl: `${config.api}/wealth/14_2.png`,
    card_type: "fortune_card",
    circulation: 5000,
    award: 6200,
    cycle: 30,
    price: "5000",
  },
  {
    id: 15,
    name: "神人武财神",
    level: "勇字传播大使",
    imageUrl: `${config.api}/wealth/15_2.png`,
    card_type: "fortune_card",
    circulation: 10000,
    award: 12500,
    cycle: 30,
    price: "10000",
  },
  {
    id: 16,
    name: "灶王武财神",
    level: "礼字传播大使",
    imageUrl: `${config.api}/wealth/16_2.png`,
    card_type: "fortune_card",
    circulation: 20000,
    award: 25200,
    cycle: 30,
    price: "20000",
  },
  {
    id: 17,
    name: "门神武财神",
    level: "智字传播大使",
    imageUrl: `${config.api}/wealth/17_2.png`,
    card_type: "fortune_card",
    circulation: 30000,
    award: 38100,
    cycle: 30,
    price: "30000",
  },
  {
    id: 18,
    name: "地界武财神",
    level: "信字传播大使",
    imageUrl: `${config.api}/wealth/18_2.png`,
    card_type: "fortune_card",
    circulation: 50000,
    award: 64000,
    cycle: 30,
    price: "50000",
  },
  {
    id: 19,
    name: "天界武财神",
    level: "财字传播大使",
    imageUrl: `${config.api}/wealth/19_2.png`,
    card_type: "fortune_card",
    circulation: 100000,
    award: 143500,
    cycle: 45,
    price: "100000",
  },
  {
    id: 20,
    name: "水界武财神",
    level: "财字传播大使",
    imageUrl: `${config.api}/wealth/20_2.png`,
    card_type: "fortune_card",
    circulation: 200000,
    award: 320000,
    cycle: 60,
    price: "200000",
  },
  {
    id: 21,
    name: "神界武财神",
    level: "财字传播大使",
    imageUrl: `${config.api}/wealth/21_2.png`,
    card_type: "fortune_card",
    circulation: 500000,
    award: 1175000,
    cycle: 90,
    price: "500000",
  },
  {
    id: 22,
    name: "至尊武财神",
    level: "富字传播大使",
    imageUrl: `${config.api}/wealth/22_2.png`,
    card_type: "fortune_card",
    circulation: 1000000,
    award: 4600000,
    cycle: 180,
    price: "1000000",
  },
];

export default nfts_list;
